<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.6 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 10748 2007-10-10 07:30:59Z cybot_tm $
 * Date: Mon, 12 May 2008 11:54:41 GMT
 */

/* Servers configuration */
$i = 0;

/* Server 192.168.0.168 (config:root) [1] */
$i++;
$cfg['Servers'][$i]['bookmarktable'] = 'pma_bookmark';
$cfg['Servers'][$i]['relation'] = 'pma_relation';
$cfg['Servers'][$i]['table_info'] = 'pma_table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma_table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma_pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma_column_info';
$cfg['Servers'][$i]['designer_coords'] = 'pma_designer_coords';
$cfg['Servers'][$i]['history'] = 'pma_history';
$cfg['Servers'][$i]['host'] = '192.168.0.168';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '22334';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['controluser'] = 'root';
$cfg['Servers'][$i]['controlpass'] = '34ccpalm';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'qzysy';
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';

/* Server 192.168.0.176 (config:root) [2] */
$i++;
$cfg['Servers'][$i]['host'] = '192.168.0.176';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '22334';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'LAC0Y*yx1Tk';


/* Server 192.168.0.164 (config:admin) [10] */
$i++;
$cfg['Servers'][$i]['host'] = '192.168.0.131';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '22334';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'LAC0Y*yx1Tk';

/* Server 192.168.0.164 (config:admin) [10] */
$i++;
$cfg['Servers'][$i]['host'] = '192.168.0.135';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '22334';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'LAC0Y*yx1Tk';

/* Server 192.168.0.164 (config:admin) [15] */
$i++;
$cfg['Servers'][$i]['host'] = '192.168.0.137';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '22334';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'LAC0Y*yx1Tk';

/* Server 192.168.0.164 (config:admin) [15] */
$i++;
$cfg['Servers'][$i]['host'] = '192.168.0.174';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '22334';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'LAC0Y*yx1Tk';

/* Server 192.168.0.167 (config:admin) [15] */
$i++;
$cfg['Servers'][$i]['host'] = '192.168.0.167';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '22334';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'LAC0Y*yx1Tk';

/* Server 192.168.0.167 (config:admin) [15] */
$i++;
$cfg['Servers'][$i]['host'] = '192.168.0.164';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '22334';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'LAC0Y*yx1Tk';

	/* End of servers configuration */

	$cfg['UploadDir'] = 'upload';
$cfg['SaveDir'] = 'save';
$cfg['blowfish_secret'] = 'hello';
$cfg['ForceSSL'] = false;
$cfg['ShowPhpInfo'] = false;
$cfg['ShowChgPassword'] = false;
$cfg['AllowArbitraryServer'] = false;
$cfg['LoginCookieRecall'] = 'something';
$cfg['LoginCookieValidity'] = 1800;
$cfg['AllowAnywhereRecoding'] = true;
$cfg['DefaultCharset'] = 'gb2312';
$cfg['RecodingEngine'] = 'iconv';
$cfg['IconvExtraParams'] = '//TRANSLIT';
?>
